# Generated by Django 5.2.14 on 2026-05-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
