# Generated by Django 5.2.14 on 2026-05-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_binuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='binuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
