# Generated by Django 5.2.14 on 2026-05-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_binuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='kategori',
            field=models.CharField(choices=[('Semua', 'Semua'), ('Transportasi', 'Transportasi'), ('Belanja', 'Belanja'), ('Makanan', 'Makanan')], default='Semua', max_length=50),
        ),
    ]
