# Generated by Django 5.2.14 on 2026-05-16 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_claimedreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='active_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.binuser'),
        ),
        migrations.AddField(
            model_name='bin',
            name='last_session_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
