# Generated by Django 5.2.14 on 2026-05-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_bin_active_user_bin_last_session_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='trigger_session',
            field=models.BooleanField(default=False),
        ),
    ]
